### PR TITLE
Try to create a syntax error

### PR DESCRIPTION
**Pull request by AA-Turner**

### CODE REVIEW

**Comment by AA-Turner** [comment]
Aha! An error:

image

image

**Comment by AA-Turner** [comment]
The first commit (non existent file) was fine in the UI, I don't know if it would be an actual issue if merged

**Comment by JelleZijlstra** [comment]
Let's merge it then :D

**Comment by AA-Turner** [comment]
I want to try both individually -- lets try the current state first which I'm pretty sure will break everything

**Comment by AA-Turner** [comment]
image

Renders an error with a dot by the line when merged

**Pull request merged**
